receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
  resourcedetection:
    detectors: [env]
    timeout: 2s
  attributes:
    actions:
      - key: environment
        value: "development"
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "demo"
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    format: json
    labels:
      resource:
        service.name: "service_name"
        service.instance.id: "instance_id"
      attributes:
        level: "level"
        event.domain: "domain"

  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [otlp/tempo]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [prometheus]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [loki]

  telemetry:
    logs:
      level: "debug"
    metrics:
      level: "detailed"
      address: "0.0.0.0:8888" 